import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/app/Components/Header/Header";
import {TooltipProvider} from "@/components/ui/tooltip";
import Footer from "@/app/Components/Footer/Footer";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt">
            <TooltipProvider>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiasedfont-[family-name:var(--font-geist-sans)] `}
                >
                    <Header/>
                        <main className="pt-24 py-12">
                            {children}
                        </main>
                    <Footer/>
                </body>
            </TooltipProvider>

        </html>
    );
}
